# Generated by Django 5.1.1 on 2024-10-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('progress_notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnotification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
