# Generated by Django 5.1.1 on 2024-10-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress_notification", "0003_alter_progressnotification_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progressnotification",
            old_name="username",
            new_name="user",
        ),
    ]
