# Generated by Django 5.1.1 on 2024-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress_notification", "0004_rename_username_progressnotification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressnotification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
