# Generated by Django 5.1.1 on 2024-10-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningPath',
        ),
    ]
