# Generated by Django 5.0.9 on 2024-10-24 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0002_initial"),
        ("exercises", "0002_initial"),
        ("quiz", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Assessment Type",
                "verbose_name_plural": "Assessment Types",
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "invited_count",
                    models.IntegerField(default=0, verbose_name="Invited Count"),
                ),
                (
                    "assessed_count",
                    models.IntegerField(default=0, verbose_name="Assessed Count"),
                ),
                (
                    "qualified_count",
                    models.IntegerField(default=0, verbose_name="Qualified Count"),
                ),
                (
                    "qualify_score",
                    models.IntegerField(default=60, verbose_name="Qualify Score"),
                ),
                (
                    "total_score",
                    models.IntegerField(default=100, verbose_name="Total Score"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("time_limit", models.IntegerField(default=0)),
                (
                    "invited_emails",
                    models.TextField(blank=True, verbose_name="Invited Candidates"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        blank=True, related_name="assessments", to="exercises.exercise"
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, related_name="assessments", to="quiz.question"
                    ),
                ),
                (
                    "assessment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="assessments.assessmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["created_at", "course"],
            },
        ),
        migrations.CreateModel(
            name="InvitedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("invitation_date", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_candidates_list",
                        to="assessments.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonRegisteredCandidateAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "score_quiz",
                    models.IntegerField(default=0, verbose_name="Quiz Score"),
                ),
                (
                    "score_ass",
                    models.IntegerField(default=0, verbose_name="Assignment Score"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("attempt_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Non-Registered Candidate Attempt",
                "verbose_name_plural": "Non-Registered Candidate Attempts",
            },
        ),
        migrations.CreateModel(
            name="StudentAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_quiz",
                    models.IntegerField(default=0, verbose_name="Quiz Score"),
                ),
                (
                    "score_ass",
                    models.IntegerField(default=0, verbose_name="Assignment Score"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("attempt_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Assignment Attempt",
                "verbose_name_plural": "Student Assignment Attempts",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_response", models.TextField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.studentassessmentattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.answeroption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
