# Generated by Django 5.0.9 on 2024-10-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('assignment', '0001_initial'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['due_date', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assignment.assignment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='quiz.quiz'),
        ),
    ]
