# Generated by Django 5.0.9 on 2024-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_options_remove_assessment_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.IntegerField(blank=True, default=0.0005),
            preserve_default=False,
        ),
    ]
