# Generated by Django 5.1.1 on 2024-10-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_assessment_total_score"),
        ("course", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="course.course",
                verbose_name="Course",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudentAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_quiz", models.IntegerField(default=0, verbose_name="Score")),
                ("score_ass", models.IntegerField(default=0, verbose_name="Score")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("attempt_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Assignment Attempt",
                "verbose_name_plural": "Student Assignment Attempts",
            },
        ),
    ]
