# Generated by Django 5.1.1 on 2024-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('learning_path', '0003_remove_learningpath_courses_step_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='course',
        ),
        migrations.AddField(
            model_name='step',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='steps', to='course.course'),
        ),
    ]
