# Generated by Django 5.0.9 on 2024-10-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0004_remove_step_course_step_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='recommended_count',
            field=models.IntegerField(default=0),
        ),
    ]
