# Generated by Django 5.0.9 on 2024-10-28 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0005_learningpath_recommended_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_learning_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
