# Generated by Django 5.0.1 on 2024-10-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='performanceanalytics',
            table='performance',
        ),
    ]
