# Generated by Django 5.0.1 on 2024-10-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analytics', '0002_alter_performanceanalytics_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='analy_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='user_id',
            new_name='user',
        ),
    ]
