# Generated by Django 5.0.1 on 2024-10-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analytics', '0005_alter_performanceanalytics_completion_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='user_id',
            new_name='user',
        ),
    ]
