# Generated by Django 5.0.1 on 2024-10-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analytics', '0006_rename_course_id_performanceanalytics_course_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='user.user'),
        ),
    ]
