# Generated by Django 5.0.1 on 2024-10-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analytics', '0007_alter_performanceanalytics_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
