# Generated by Django 5.1.1 on 2024-10-15 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
        (
            "performance_analytics",
            "0010_rename_course_id_performanceanalytics_course_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceanalytics",
            name="average_score",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name="performanceanalytics",
            name="completion_rate",
            field=models.IntegerField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name="performanceanalytics",
            name="course",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="performanceanalytics",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="performanceanalytics",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
