# Generated by Django 5.0.9 on 2024-10-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('module_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('modules', models.ManyToManyField(blank=True, help_text='Modules assigned to this role.', related_name='role_modules', to='module_group.module', verbose_name='modules')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role.', related_name='role_permissions', to='auth.permission', verbose_name='permissions')),
            ],
        ),
    ]
