# Generated by Django 5.1.1 on 2024-10-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="date",
            new_name="issue_date",
        ),
    ]
