# Generated by Django 5.1.2 on 2024-10-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercourseprogress',
            table='progress_progress',
        ),
    ]
