# Generated by Django 5.1.1 on 2024-10-22 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
        ("user_progress", "0002_alter_usercourseprogress_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserCourseProgress",
            new_name="UserProgress",
        ),
    ]
