# Generated by Django 5.1.1 on 2024-10-15 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_insights", "0002_alter_ai_insights_course"),
        ("course", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AI_Insights",
            new_name="AIInsights",
        ),
        migrations.RenameField(
            model_name="aiinsights",
            old_name="username",
            new_name="user",
        ),
    ]
