# Generated by Django 5.0.9 on 2024-10-24 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0002_initial"),
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_name",
                    models.CharField(max_length=100, verbose_name="Assignment Name"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Assignment Content"
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Score")),
                ("note", models.TextField(blank=True, verbose_name="Notes")),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "coding_exercises",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignments",
                        to="exercises.exercise",
                        verbose_name="Coding Exercises",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="course.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["start_date"],
            },
        ),
    ]
